import React, { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Sparkles, BrainCircuit, Loader2 } from "lucide-react";
import { useMutation } from "@tanstack/react-query";
import api from "@/api/axios";

const AIFeedback = ({ gradeId, initialFeedback, isReviewed }) => {
  const [feedback, setFeedback] = useState(initialFeedback);
  const [displayedText, setDisplayedText] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  const { mutate: requestFeedback, isPending } = useMutation({
    mutationFn: async () => {
      const response = await api.post("/api/AI-Assessment/feedback", { gradeId });
      return response.data.feedback;
    },
    onSuccess: (data) => {
      setFeedback(data);
    },
  });

  useEffect(() => {
    if (!feedback && gradeId) {
      requestFeedback();
    }
  }, [feedback, gradeId, requestFeedback]);

  useEffect(() => {
    if (feedback && displayedText.length < feedback.length) {
      setIsTyping(true);
      const timeout = setTimeout(() => {
        setDisplayedText(feedback.slice(0, displayedText.length + 1));
      }, 20); // Typing speed
      return () => clearTimeout(timeout);
    } else {
      setIsTyping(false);
    }
  }, [feedback, displayedText]);

  if (isPending) {
    return (
      <Card className="border-primary/20 bg-primary/5 animate-pulse">
        <CardContent className="p-6 flex flex-col items-center justify-center space-y-4">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
          <p className="text-sm font-medium text-primary">AI Tutor is analyzing your performance...</p>
        </CardContent>
      </Card>
    );
  }

  if (!feedback) return null;

  return (
    <Card className="border-primary/30 bg-gradient-to-br from-primary/5 to-accent/5 shadow-lg border-2 relative overflow-hidden group animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Glowing background effect */}
      <div className="absolute -top-24 -right-24 w-48 h-48 bg-primary/10 rounded-full blur-3xl group-hover:bg-primary/20 transition-all duration-500" />
      <div className="absolute -bottom-24 -left-24 w-48 h-48 bg-accent/10 rounded-full blur-3xl group-hover:bg-accent/20 transition-all duration-500" />
      
      <CardHeader className="pb-2 relative z-10">
        <CardTitle className="flex items-center gap-2 text-xl font-black text-primary">
          <Sparkles className="w-5 h-5 animate-pulse text-accent" />
          {isReviewed ? "AI Insights (Reviewed by Teacher)" : "AI Tutor Feedback"}
          <BrainCircuit className="w-5 h-5 ml-auto opacity-20" />
        </CardTitle>
      </CardHeader>
      
      <CardContent className="relative z-10">
        <div className="prose prose-sm max-w-none text-foreground leading-relaxed whitespace-pre-wrap">
          {displayedText}
          {isTyping && <span className="inline-block w-2 h-4 ml-1 bg-primary animate-bounce" />}
        </div>
        
        <div className="mt-4 pt-4 border-t border-primary/10 flex items-center justify-between">
          <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
            Generated by LearnHub Smart Brain
          </p>
          <div className="flex gap-1">
             <div className="w-1.5 h-1.5 rounded-full bg-primary/30" />
             <div className="w-1.5 h-1.5 rounded-full bg-primary/50" />
             <div className="w-1.5 h-1.5 rounded-full bg-primary/70" />
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default AIFeedback;
